# Generated by OpenCode on 2026-06-11

from django.db import migrations, models

import exhibition.models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0005_exhibition_call_proposals"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitorsettings",
            name="proposal_field_settings",
            field=models.JSONField(
                default=exhibition.models.default_proposal_field_settings
            ),
        ),
    ]
