from django.urls import path
from eventyay.api.urls import event_router
from eventyay.common.urls import OrganizerSlugConverter  # noqa: F401

from .api import (
    ExhibitorAuthView,
    ExhibitorInfoViewSet,
    LeadCreateView,
    LeadRetrieveView,
    LeadUpdateView,
    TagListView,
)
from .views import (
    ExhibitionQuestionCreateView,
    ExhibitionQuestionDeleteView,
    ExhibitionQuestionEditView,
    ExhibitionQuestionListView,
    ExhibitorCopyKeyView,
    ExhibitorCreateView,
    ExhibitorDeleteView,
    ExhibitorEditView,
    ExhibitorListView,
    ProposalDetailView,
    ProposalListView,
    PublicCallView,
    PublicExhibitorDetailView,
    PublicExhibitorListView,
    SettingsView,
    SponsorGroupFrontPageToggleView,
    SponsorGroupReorderView,
    UserProposalCreateView,
    UserProposalEditView,
    UserProposalListView,
)

urlpatterns = [
    path(
        "<str:organizer>/<str:event>/exhibition/",
        PublicExhibitorListView.as_view(),
        name="public_list",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/",
        PublicCallView.as_view(),
        name="public_call",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/submit/",
        UserProposalCreateView.as_view(),
        name="proposal.add",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/me/",
        UserProposalListView.as_view(),
        name="proposal.user_list",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/proposals/<str:code>/",
        UserProposalEditView.as_view(),
        name="proposal.user_edit",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/<int:pk>/",
        PublicExhibitorDetailView.as_view(),
        name="public_detail",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings",
        SettingsView.as_view(active_tab="exhibitors"),
        name="settings",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/exhibitors",
        SettingsView.as_view(active_tab="exhibitors"),
        name="settings.exhibitors",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/sponsors",
        SettingsView.as_view(active_tab="sponsors"),
        name="settings.sponsors",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/call",
        SettingsView.as_view(active_tab="call"),
        name="settings.call",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/sponsors/groups/<int:pk>/toggle-front-page",
        SponsorGroupFrontPageToggleView.as_view(),
        name="toggle_front_page",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/sponsors/groups/reorder",
        SponsorGroupReorderView.as_view(),
        name="reorder_groups",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>",
        ExhibitorListView.as_view(),
        name="info",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call",
        ProposalListView.as_view(),
        name="proposal.list",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/proposals/<str:code>",
        ProposalDetailView.as_view(),
        name="proposal.detail",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/questions",
        ExhibitionQuestionListView.as_view(),
        name="call.questions",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/questions/add",
        ExhibitionQuestionCreateView.as_view(),
        name="call.questions.add",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/questions/<int:pk>/edit",
        ExhibitionQuestionEditView.as_view(),
        name="call.questions.edit",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/questions/<int:pk>/delete",
        ExhibitionQuestionDeleteView.as_view(),
        name="call.questions.delete",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/add",
        ExhibitorCreateView.as_view(),
        name="add",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/edit/<int:pk>",
        ExhibitorEditView.as_view(),
        name="edit",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/delete/<int:pk>",
        ExhibitorDeleteView.as_view(),
        name="delete",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/copy_key/<int:pk>",
        ExhibitorCopyKeyView.as_view(),
        name="copy_key",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/auth",
        ExhibitorAuthView.as_view(),
        name="exhibitor-auth",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/lead/create",
        LeadCreateView.as_view(),
        name="lead-create",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/lead/retrieve",
        LeadRetrieveView.as_view(),
        name="lead-retrieve",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/tags",
        TagListView.as_view(),
        name="exhibitor-tags",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/lead/<str:lead_id>/update",
        LeadUpdateView.as_view(),
        name="lead-update",
    ),
]

event_router.register("exhibitors", ExhibitorInfoViewSet, basename="exhibitorinfo")
